// Sample data shown on first load so charts/table aren't empty.
// Cleared the moment the user adds or deletes anything (they own their list).

export const seedJobs = [
  {
    id: 'seed-1',
    company: 'Anthropic',
    title: 'Frontend Engineer',
    location: 'Remote',
    type: 'full_time',
    date: '2026-05-12',
    status: 'interview',
    source: 'https://anthropic.com/careers',
    contact: 'recruiting@anthropic.com',
    notes: 'Round 2 scheduled.',
    followUp: '2026-06-25',
  },
  {
    id: 'seed-2',
    company: 'Figma',
    title: 'Design Engineer Intern',
    location: 'San Francisco, CA',
    type: 'internship',
    date: '2026-04-30',
    status: 'no_response',
    source: 'LinkedIn',
    contact: '',
    notes: '',
    followUp: '2026-06-28',
  },
  {
    id: 'seed-3',
    company: 'Linear',
    title: 'Product Engineer',
    location: 'Remote',
    type: 'remote',
    date: '2026-04-02',
    status: 'offer',
    source: 'https://linear.app/careers',
    contact: 'Alex (recruiter)',
    notes: 'Verbal offer received.',
    followUp: '',
  },
  {
    id: 'seed-4',
    company: 'Notion',
    title: 'Frontend Engineer (Contract)',
    location: 'Remote',
    type: 'contract',
    date: '2026-03-18',
    status: 'rejected',
    source: 'https://notion.so/careers',
    contact: '',
    notes: 'Position closed.',
    followUp: '',
  },
  {
    id: 'seed-5',
    company: 'Stripe',
    title: 'UI Engineer',
    location: 'Dublin, Ireland',
    type: 'full_time',
    date: '2026-05-28',
    status: 'no_response',
    source: 'https://stripe.com/jobs',
    contact: '',
    notes: '',
    followUp: '2026-07-01',
  },
]
